{% set name = "smdebug-rulesconfig" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/sagemaker-debugger-rulesconfig/archive/v{{ version }}.tar.gz
  sha256: 0be59d7bb7e0c8b0fff5f8eb4b176bcdbd275a5d623261126e7ad41fa951cc8c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - smdebug_rulesconfig

about:
  home: https://github.com/awslabs/sagemaker-debugger-rulesconfig
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Amazon SageMaker Debugger is designed to be a debugger for machine learning models..
  dev_url: https://github.com/awslabs/sagemaker-debugger-rulesconfig

extra:
  recipe-maintainers:
    - rluria14
    - benhuff
    - oblute
