{% set name = "smdebug-rulesconfig" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/sagemaker-debugger-rulesconfig/archive/v{{ version }}.tar.gz
  sha256: b784903fc526958a97733f1ec833c97895cec9e6b978743fd816917a94927407

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - smdebug_rulesconfig

about:
  home: https://github.com/awslabs/sagemaker-debugger-rulesconfig
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Amazon SageMaker Debugger is designed to be a debugger for machine learning models..
  dev_url: https://github.com/awslabs/sagemaker-debugger-rulesconfig

extra:
  recipe-maintainers:
    - rluria14
    - benhuff
    - oblute
